"""Compatibility exports for calibrated spherical-ball pose estimation."""

from .ball_detection import (
    BallDetectionReport,
    BallDetectionResult,
    BallColorProfile,
    default_ball_color_profiles,
    detect_ball,
    detect_ball_detailed,
    detect_ball_candidates,
    detect_balls,
    detect_balls_detailed,
    detect_partial_ball,
    estimate_ball_pose,
    estimate_ball_pose_from_contour,
    fit_sphere_pose,
    load_ball_color_profiles,
    project_sphere_limb,
    recover_sphere_center_from_ellipse,
    reset_ball_color_profile,
    sample_ball_color_profile,
    save_ball_color_profiles,
    set_ball_radius,
)

__all__ = [
    "BallDetectionReport",
    "BallDetectionResult",
    "BallColorProfile",
    "default_ball_color_profiles",
    "detect_ball",
    "detect_ball_detailed",
    "detect_ball_candidates",
    "detect_balls",
    "detect_balls_detailed",
    "detect_partial_ball",
    "estimate_ball_pose",
    "estimate_ball_pose_from_contour",
    "fit_sphere_pose",
    "load_ball_color_profiles",
    "project_sphere_limb",
    "recover_sphere_center_from_ellipse",
    "reset_ball_color_profile",
    "sample_ball_color_profile",
    "save_ball_color_profiles",
    "set_ball_radius",
]
