"""User-adjustable settings for the 6D pose application."""

CAMERA_INDEX = "/dev/video4"
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
CAMERA_FORMAT = "MJPG"
CAMERA_FPS = 30

# Actual printed ArUco black-square side length in metres.
# Example: 40 mm marker = 0.040 m
MARKER_SIZE_M = 0.040

MIN_OBJECT_AREA = 5000

# The calibration file must contain camera_matrix, dist_coeffs,
# image_width, and image_height saved by np.savez.
CALIBRATION_FILE = "camera_calibration.npz"
CALIBRATION_BOARD_SIZE = (7, 7)
CALIBRATION_SQUARE_SIZE_M = 0.025
CALIBRATION_REQUIRED_VIEWS = 20

SQUARE_ASPECT_RATIO_MAX = 1.15
MAX_RIGHT_ANGLE_COSINE = 0.15
CIRCLE_MIN_CIRCULARITY = 0.78
CIRCLE_MAX_AXIS_RATIO = 1.15

# The current cube is a dark, unmarked 30 mm cube.  Its silhouette is
# therefore detected separately from the generic square/circle detector.
CUBE_SIZE_M = 0.030
CUBE_DARK_THRESHOLD = 100
CUBE_MIN_AREA = 1200
# Keep the historical coarse epsilon for compatibility, but detection now
# evaluates the four fractions below so one-axis transition silhouettes retain
# their five/six outer vertices.
CUBE_APPROX_EPSILON = 0.02
CUBE_APPROX_EPSILON_FRACTIONS = (0.005, 0.008, 0.012, 0.020)
CUBE_LOCAL_MAPPING_LIMIT = 3
CUBE_POSE_TIME_CONSTANT_S = 0.12
CUBE_MAX_HOLD_SECONDS = 0.75
CUBE_MAX_TRACK_ERROR_PIXELS = 60.0
CUBE_MAX_FIT_ERROR_PIXELS = 3.0
CUBE_MAX_FIT_ERROR_FRACTION = 0.03
CUBE_MAX_PLANAR_FIT_ERROR_PIXELS = 15.0
CUBE_MAX_CENTER_SPEED_MPS = 1.0
CUBE_MAX_Z_SPEED_MPS = 0.75
CUBE_MAX_ROTATION_SPEED_DEG_PER_S = 360.0
CUBE_MAX_PLANAR_ROTATION_SPEED_DEG_PER_S = 540.0
CUBE_TEXT_GAP_PIXELS = 60
MILLIMETRES_PER_METRE = 1000.0

# OpenCV draws frame axes as X=red, Y=green, Z=blue.
AXIS_X_COLOR = (0, 0, 255)
AXIS_Y_COLOR = (0, 255, 0)
AXIS_Z_COLOR = (255, 0, 0)
POSE_TEXT_COLOR = (255, 255, 255)
POSE_TEXT_SHADOW_COLOR = (0, 0, 0)
POSE_TEXT_FONT_SCALE = 0.9
POSE_TEXT_LINE_HEIGHT = 30
POSE_TEXT_THICKNESS = 2
POSE_GUIDE_FONT_SCALE = 0.6
POSE_GUIDE_LINE_HEIGHT = 22

CAMERA_READ_RETRIES = 5
CAMERA_REOPEN_ATTEMPTS = 3
CAMERA_RETRY_DELAY_S = 0.02

CALIBRATION_MAX_RMS_ERROR_PIXELS = 1.0
CALIBRATION_MAX_VIEW_ERROR_PIXELS = 2.0
CALIBRATION_DUPLICATE_CENTER_DISTANCE = 0.06
CALIBRATION_DUPLICATE_LOG_AREA_DISTANCE = 0.10
CALIBRATION_DUPLICATE_ANGLE_DEG = 6.0
